default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: library_development
  username: <%= ENV['DATABASE_USERNAME'] %>


test:
  <<: *default
  database: library_test
  username: <%= ENV['DATABASE_USERNAME'] %>

production:
  <<: *default
  database: library_production
  username: <%= ENV['DATABASE_USERNAME'] %>
